services:

  app-wse:
    build:
      context: ./app-wse
    volumes:
      - ./app-wse:/app-wse
    ports:
      - 8000:8000
    env_file:
      - ./app-wse/.env
    command:
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db-wse-postgres

  db-wse-postgres:
    image: postgres:15
    volumes:
      - ./volumes/db-wse:/var/lib/postgresql/data
    env_file:
      - ./app-wse/.env.postgres

volumes:
  db-wse: