services:

  app-wse:
    build:
      context: ./app-wse
    volumes:
      - ./app-wse:/app-wse
      - ./volumes/static:/app-wse/static
    expose:
      - 8000
    env_file:
      - ./app-wse/.env
    command:
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db-wse-postgres

  db-wse-postgres:
    image: postgres:15
    volumes:
      - ./volumes/db-wse:/var/lib/postgresql/data
    env_file:
      - ./app-wse/.env.postgres

  web-server:
    build:
      context: ./nginx
    volumes:
      - ./volumes/static:/static
    ports:
      - 80:80
    depends_on:
      - app-wse

volumes:
  db-wse:
  static:
