[tool.poetry]
name = "wselfedu"
version = "0.1.0"
description = ""
authors = ["Sergei Mikurov <454004@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"
django-bootstrap5 = "^23.3"
django = "4.2.6"
django-filter = "^23.5"
django-crispy-forms = "^2.1"
crispy-bootstrap5 = "^2023.10"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
faker = "^21.0.0"
coverage = "^7.3.3"
django-etensions = "^3.2.3"
ipython = "^8.18.1"
notebook = "6.5.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
